spring:
  application:
    name: CERPS-Hashkin

spring.http.client:
  connect-timeout: 5s
  read-timeout: 10s

scheduling:
  enabled: true
  exchange-rates:
    rate: 3600000

api:
  fixer:
    url: https://data.fixer.io/api
    access-key: ${FIXER_API_KEY:}
  exchangerates:
    url: https://api.exchangeratesapi.io/v1
    access-key: ${EXCHANGERATES_API_KEY:}
  currencyapi:
    url: https://api.currencyapi.com/v3
    access-key: ${CURRENCYAPI_KEY:}

cache:
  exchange-rates:
    ttl: 3600

exchange-rates:
  base-currency: EUR
